User login frontend
hack4impact-calpoly/happy-hats pull request #8
Opened 2021-02-16 03:26 UTC by shadhussain12

2021-02-16 06:34 UTC, bglossner commented
Hey, please merge this branch with the current main branch and be sure to not include the node_modules, which should be done for you with the .gitignore. As you can see, there are 2100 files changed... not great for reviewing purposes.

2021-02-22 18:02 UTC, bglossner requested changes

2021-02-22 18:02 UTC, bglossner commented on frontend/package.json
> +>>>>>>> 2be1b59ea728e92048833d32a823a925fce87341
These are merge markers that we don't want. Make sure to fix merge conflicts.

2021-02-24 17:02 UTC, AnnaReid22 requested changes
Node_modules is still present in this PR even though you have added it to the .gitignore. Please remove node_modules so that we can merge with main!

2021-02-24 20:43 UTC, bglossner approved these changes

2021-02-24 20:44 UTC, AnnaReid22 approved these changes

2021-02-24 20:46 UTC, merged